### PR TITLE
Add aliases to allow/revoke security group ingress based on my public IP

### PR DESCRIPTION
**Pull request by edersonmf**
This will allow:
* Add inbound rule to a security group allowing access on a given port for my public ip
* Add inbound rule to a security group allowing all traffic for my public ip
* Add inbound rule to a security group revoking access on a given port for my public ip
* Add inbound rule to a security group revoking all traffic for my public ip

### CODE REVIEW

**Comment by kyleknap** [comment]
Thanks for the pull request. The general aliases look good to me that you are adding. The only thing that I noticed is that you are using ``checkip.amazon.com``.  An existing alias that got added a couple of weeks ago used ``dig`` and ``myip.opends.com`` to figure out the IP: https://github.com/awslabs/awscli-aliases/blob/master/alias#L48. From researching, this method seems a bit more robust as it better deals with ISP and firewalls. What is your thoughts on using this method instead? I would like to see all of the IP resolving logic stay the same across aliases.

**Comment by edersonmf** [comment]
I think using the same logic across aliases is the best approach.
I understand using `dig` is a better choice. Let's go for it.

**Comment by kyleknap** [comment]
Hmm looks like when I merged the other alias PR's. It caused merge conflicts with this one. @edersonmf Could you rebase off master?

**Comment by edersonmf** [comment]
Yes, sure! Rebase is done.

**Comment by kyleknap** [comment]
Thanks! Merging.

**Pull request merged**
