### PR TITLE
Add alias to make docker log in to AWS ECR

### PR DESCRIPTION
**Pull request by edersonmf**

### CODE REVIEW

**Comment by kyleknap** [comment]
Thanks for the pull request. It looks good to me. Could you possibly rebase this off of the master branch and confirm this contribution is under the terms of the [MIT license](https://github.com/awslabs/awscli-aliases/blob/master/LICENSE)?

**Comment by edersonmf** [comment]
Thanks for the feedback!
Rebase off of master is done and I confirm this contribution is under the terms of the [MIT license](https://github.com/awslabs/awscli-aliases/blob/master/LICENSE)?

**Comment by tchia04** [comment]
Just FYI. When I tried to run "aws docker-ecr-login" on a mac, I got the following error.

<pre>
tonychia@Tonys-MacBook-Pro ~/.aws/cli $ which base64
/usr/bin/base64
tonychia@Tonys-MacBook-Pro ~/.aws/cli $ base64 --help
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
tonychia@Tonys-MacBook-Pro ~/.aws/cli $
</pre>

It seems on the Mac, it's using a capital -D for decode but on Redhat/Ubuntu, it's using lower case -d for decode. So I would suggest using "--decode" instead which would work on both Mac and Linux.

Another suggestion that I have is to remove the "-e none" since it was complaining about that flag is going to be removed 

<pre>

tonychia@Tonys-MacBook-Pro ~/.aws/cli $ aws docker-ecr-login
Flag --email has been deprecated, will be removed in 1.14.
Login Succeeded
tonychia@Tonys-MacBook-Pro ~/.aws/cli $

</pre>


After making those two changes, it worked perfectly on a Mac.

<pre>
tonychia@Tonys-MacBook-Pro ~/.aws/cli $ aws docker-ecr-login
Login Succeeded
tonychia@Tonys-MacBook-Pro ~/.aws/cli $
</pre>

**Comment by edersonmf** [comment]
Good catch! I've incorporated the suggestions you pointed out.

**Comment by kyleknap** [comment]
Awesome. Merging.

**Pull request merged**
