### PR TITLE
added tostring_with_jq and tostring_with_jq

### PR DESCRIPTION
**Pull request by tchia04**
so it can be used in standalone mode or in other alias command that requires a policy document in string format

standalone mode 

<pre>
tonychia@Tonys-MacBook-Pro ~ $ cat book.json
{
  "store" : {
  "book" : [
  {
  "category" : "reference",
  "author" : "Nigel Rees",
  "title" : "Sayings of the Century",
  "price" : 8.95
  },
  {
  "category" : "fiction",
  "author" : "Evelyn Waugh",
  "title" : "Sword of Honour",
  "price" : 12.99
  },
  {
  "category" : "fiction",
  "author" : "Herman Melville",
  "title" : "Moby Dick",
  "isbn" : "0-553-21311-3",
  "price" : 8.99
  },
  {
  "category" : "fiction",
  "author" : "J. R. R. Tolkien",
  "title" : "The Lord of the Rings",
  "isbn" : "0-395-19395-8",
  "price" : 22.99
  }
  ],
  "bicycle" : {
  "color" : "red",
  "price" : 19.95
  }
  },
  "expensive" : 10
}
tonychia@Tonys-MacBook-Pro ~ $ vi book.json
tonychia@Tonys-MacBook-Pro ~ $ alias
tonychia@Tonys-MacBook-Pro ~ $ aws tostring_with_jq book.json
"{\"store\":{\"book\":[{\"category\":\"reference\",\"author\":\"Nigel Rees\",\"title\":\"Sayings of the Century\",\"price\":8.95},{\"category\":\"fiction\",\"author\":\"Evelyn Waugh\",\"title\":\"Sword of Honour\",\"price\":12.99},{\"category\":\"fiction\",\"author\":\"Herman Melville\",\"title\":\"Moby Dick\",\"isbn\":\"0-553-21311-3\",\"price\":8.99},{\"category\":\"fiction\",\"author\":\"J. R. R. Tolkien\",\"title\":\"The Lord of the Rings\",\"isbn\":\"0-395-19395-8\",\"price\":22.99}],\"bicycle\":{\"color\":\"red\",\"price\":19.95}},\"expensive\":10}"
tonychia@Tonys-MacBook-Pro ~ $

</pre>

Example using jp instead of jq
<pre>
tonychia@Tonys-MacBook-Pro ~ $ aws tostring_with_jp book.json
"{\"expensive\":10,\"store\":{\"bicycle\":{\"color\":\"red\",\"price\":19.95},\"book\":[{\"author\":\"Nigel Rees\",\"category\":\"reference\",\"price\":8.95,\"title\":\"Sayings of the Century\"},{\"author\":\"Evelyn Waugh\",\"category\":\"fiction\",\"price\":12.99,\"title\":\"Sword of Honour\"},{\"author\":\"Herman Melville\",\"category\":\"fiction\",\"isbn\":\"0-553-21311-3\",\"price\":8.99,\"title\":\"Moby Dick\"},{\"author\":\"J. R. R. Tolkien\",\"category\":\"fiction\",\"isbn\":\"0-395-19395-8\",\"price\":22.99,\"title\":\"The Lord of the Rings\"}]}}"
tonychia@Tonys-MacBook-Pro ~ $
</pre>

### CODE REVIEW

**Comment by kyleknap** [comment]
@tchia04 

Thanks for the pull request! I would like to pull this functionality in. The only thing I wonder is if it makes sense to have a single ``tostring`` alias that calls one of the tools (probably preferably ``jp`` since it use the same functionality as ``--query``). Could you elaborate on the reason for having both aliases? Also if we have two aliases, I think I would prefer it to use dashes to be consistent with the rest of the CLI.

Also could you please confirm this contribution is under the terms of the [MIT license](https://github.com/awslabs/awscli-aliases/blob/master/LICENSE).

**Comment by tchia04** [comment]
Hi Kyle,
Originally I was thinking of having one tostring alias too. However I can imagine someone who may have only jp installed and other people have only jq installed.  I don't know the syntax or if it's possible to do "if jq is installed then use jp, else use jq" so I created two different alias.  I have replaced the underscore with dashes and I confirm this contribution is under the terms of the MIT license.

**Comment by kyleknap** [comment]
@tchia04 
Awesome. Makes sense. I do not think we should add a conditional either so that we avoid overcomplicating the alias.

How about as a compromise, we just rename the ``tostring-with-jp`` to ``tostring`` and we keep the ``tostring-jq`` alias as a fallback? Ideally I would prefer promoting one alias (and that being ``jp`` for the same reasons that I stated before) over the other in order to give some guidance between which one to chose if an individual is new to the project.

**Comment by tchia04** [comment]
Done.

**Comment by kristianpaul** [comment]
This change should update the  docs as well in order to point that you need jq installed as an additional requirement...  if is an agreement to start adding dependencies to the aliases

**Comment by kyleknap** [comment]
@kristianpaul  Good point about the README!

@tchia04 Thanks for updating. Merging

**Pull request merged**
