### PR TITLE
Add alias to authorize my IP for SSH access to a security group

### PR DESCRIPTION
**Pull request by tylerjryan**
I should note that this only works on MacOS and linux systems with `dig` installed. I know that this won't work out of the box on windows, and I'm not sure if there are linux distributions that don't come with dig. 

This is one of the aliases from the reinvent presentation on the AWS CLI, so maybe Kyle Knapp, the presenter, can provide some insight.

### CODE REVIEW

**Comment by kyleknap** [comment]
@tylerjryan 

Thanks for the contribution!  I definitely want to get the ``authorize-my-ip`` into the alias file. So I have a few different versions of implementing the alias. For the re:Invent talk, I literally hard coded my CIDR block. However, I do have implementations of this alias that queries an external service to determine my IP, which is what what you do. In the end though the CLI command that I use is the same, it just comes down to how the IP/CIDR block is provided.

I think I would want to go with your approach mainly because:
1) It is really helpful if you do not know your IP
2) The solution works right out of the box (i.e. you would not have to force the user to figure out their IP and hard code that in their configuration)

The only thing that I need to do is double check is that there are no security issues with this approach, but I think it should be fine.

**Comment by tylerjryan** [comment]
Sounds great! Happy to help, and nice to hear from you. I really enjoyed the presentation and learned a lot, despite having used the CLI very extensively. 

Also, note that I chose `group-name` instead of `group-id`. We can PR whichever you prefer, I just like name because it saves me from needing to look up the id.

**Comment by kyleknap** [comment]
Thanks!  I am really glad you enjoyed the talk and got a lot out of it.

So I actually did not notice that you were using ``--group-name`` before. After looking at it though, we may want to change that to ``--group-id`` as based on the docs: http://docs.aws.amazon.com/cli/latest/reference/ec2/authorize-security-group-ingress.html you have to use ``--group-id`` if you are using a non-default vpc, which is what I was doing in my talk, and that works for any type of VPC.

As a compromise because I think using the group name is easier to remember, maybe we could add a ``get-group-id`` alias that given a security group name retrieves you a group id?

This may be a stretch idea, but we could leverage another cool aspect about aliases where you can wrap them. So if we had the ``get-group-id`` alias and ``authorize-my-ip`` alias. We could easily build an ``authorize-my-ip-by-name`` alias with a definition that consisted of:
```
authorize-my-ip-by-name = 
   !f() {
      group_id=$(aws get-group-id "${1}")
      aws authorize-my-ip "$group_id"
   }
```
The upside is that you do not have to copy and paste the alias definition and avoid violating DRY. The downside is that you will be making an uneeded ``describe-security-group`` call to get the group id if your VPC allows for it so it may be better to have it hardcoded to save from making that extra API call.

**Comment by tylerjryan** [comment]
I think those are great ideas. What I really like about your approach is that it is very instructive. It demonstrates alias wrapping and also makes use of backend filtering and using the `query` parameter. These were some key points from your talk. 

Take a look and see what you think.

**Comment by kyleknap** [comment]
@tylerjryan 

Looks good to me! Thanks for making the updates.

Before I merge the pull request, could you please confirm this contribution is under the terms of the [MIT license](https://github.com/awslabs/awscli-aliases/blob/master/LICENSE).

**Comment by tylerjryan** [comment]
confirmed!

**Comment by kyleknap** [comment]
Thanks again! Merging.

**Pull request merged**
